baseUrl: /
languageCode: en-us
theme: terminal
paginate: 5

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # ["orange", "blue", "red", "green", "pink"]
  themeColor: orange
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 5
  # show selector to switch language
  showLanguageSelector: false
  # set theme to full screen width otherwise it is 80 characters
  fullWidthTheme: false
  # center theme with default width
  centerTheme: false

languages:
  en:
    languageName: English
    title: pi-tau

    params:
      subtitle: My personal blog where I share some cool content about deep learning, reinforcement learning and other CS stuff.
      keywords: ai, deep learning, reinforcement learning, rl, generative models, research, computer science, computer vision, nlp, pytorch
      menuMore: Show more
      readMore: Read more
      readOtherPosts: Read other posts
      logo:
        logoText: Terminal
        logoHomeLink: /

    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: posts
        name: Posts
        url: /posts
      - identifier: contact
        name: Contact
        url: /contact

enableRobotsTXT: true
